# Generated by Django 6.1.1 on 2026-09-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_exam_examattempt_examquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='intro_video_url',
            field=models.CharField(blank=True, default='', help_text='YouTube (Standard / Unlisted), YouTube Live, or Vimeo video URL for course intro / live class.', max_length=500),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.CharField(blank=True, default='', help_text='YouTube (Standard/Unlisted/Live), Vimeo, or Direct video URL.', max_length=500),
        ),
    ]
