# Generated by Django 6.1.1 on 2026-09-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_intro_video_url_alter_lesson_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpost',
            name='category',
            field=models.CharField(choices=[('announcement', '📢 নোটিশ / ঘোষণা'), ('tips', '💡 স্টাডি টিপস ও ট্রিকস'), ('question', '❓ প্রশ্ন ও সমাধান'), ('motivation', '🔥 মোটিভেশন ও অভিজ্ঞতা'), ('general', '📢 সাধারণ আলোচনা')], default='general', max_length=50),
        ),
    ]
