# Generated by Django 6.1.1 on 2026-09-25 18:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_feedpost_category'),
        ('tenants', '0007_tenant_footer_style_tenant_header_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='বিবরণ / শিরোনাম', max_length=255)),
                ('transaction_type', models.CharField(choices=[('income', 'আয় (Income)'), ('expense', 'ব্যয় (Expense)')], default='income', max_length=20)),
                ('category', models.CharField(choices=[('course_fee', 'কোর্স ফি / ভর্তি'), ('book_sale', 'বই বিক্রয়'), ('offline_payment', 'অফলাইন ফি / ক্যাশ'), ('other_income', 'অন্যান্য আয়'), ('instructor_salary', 'শিক্ষক / মেন্টর সম্মানী'), ('marketing_ads', 'মার্কেটিং ও ফেসবুক অ্যাড'), ('server_software', 'সার্ভার, ডোমেন ও সফটওয়্যার'), ('office_utility', 'অফিস ভাড়া ও ইউটিলিটি'), ('other_expense', 'অন্যান্য ব্যয়')], default='course_fee', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(default='bKash', help_text='bKash, Nagad, Rocket, Bank, Cash', max_length=50)),
                ('reference_no', models.CharField(blank=True, default='', help_text='TrxID / Invoice No / Receipt No', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LiveClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='লাইভ ক্লাসের বিষয় / শিরোনাম', max_length=255)),
                ('platform', models.CharField(choices=[('zoom', 'Zoom Meeting'), ('meet', 'Google Meet'), ('youtube_live', 'YouTube Live'), ('facebook_live', 'Facebook Live'), ('custom', 'অন্যান্য লাইভ লিংক')], default='zoom', max_length=30)),
                ('meeting_url', models.URLField(help_text='Zoom/Meet/YouTube Live URL', max_length=500)),
                ('meeting_id', models.CharField(blank=True, default='', help_text='Meeting ID (ঐচ্ছিক)', max_length=100)),
                ('passcode', models.CharField(blank=True, default='', help_text='Passcode / Password (ঐচ্ছিক)', max_length=100)),
                ('instructor_name', models.CharField(default='কোর্স ইন্সট্রাক্টর', max_length=150)),
                ('scheduled_at', models.DateTimeField(help_text='লাইভ ক্লাসের তারিখ ও সময়')),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('status', models.CharField(choices=[('upcoming', 'আসন্ন (Upcoming)'), ('live_now', '🔴 লাইভ চলছে (Live Now)'), ('completed', 'সম্পন্ন (Completed)')], default='upcoming', max_length=20)),
                ('recording_url', models.URLField(blank=True, default='', help_text='ক্লাস শেষের রেকর্ডিং লিংক', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='courses.course')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
