# Generated by Django 6.1.1 on 2026-09-14 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('tenants', '0006_tenant_landing_template_tenantmenuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('image_url', models.URLField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('author_name', models.CharField(default='একাডেমি টিম', max_length=150)),
                ('category', models.CharField(default='ভর্তি পরামর্শ', help_text='e.g. প্রস্তুতি কৌশল, নোটিশ, টিপস', max_length=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/covers/')),
                ('cover_url', models.URLField(blank=True, default='')),
                ('excerpt', models.TextField(blank=True, help_text='Short teaser summary')),
                ('content', models.TextField(blank=True, help_text='Full post content (Markdown or HTML)')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_blog_slug_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('author', models.CharField(blank=True, default='একাডেমি ফ্যাকাল্টি', max_length=255)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/covers/')),
                ('cover_url', models.URLField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('edition', models.CharField(blank=True, default='২০২৬ সংস্করণ', max_length=100)),
                ('pages', models.PositiveIntegerField(default=0)),
                ('in_stock', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('preview_pdf_url', models.URLField(blank=True, default='')),
                ('buy_url', models.CharField(blank=True, default='', max_length=500)),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_book_slug_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='FreeResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('resource_type', models.CharField(choices=[('PDF_NOTE', 'PDF নোট ও শিট'), ('MODEL_TEST', 'মডেল টেস্ট ও প্রশ্নব্যাংক'), ('LECTURE_SHEET', 'লেকচার শিট'), ('SUGGESTION', 'পরীক্ষার সাজেশন'), ('VIDEO_GUIDE', 'ভিডিও গাইড')], default='PDF_NOTE', max_length=50)),
                ('category', models.CharField(default='এইচএসসি ও ভর্তি', help_text='e.g. HSC, DU, Medical, BUET', max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/files/')),
                ('file_url', models.URLField(blank=True, default='', help_text='External Google Drive / Dropbox link')),
                ('video_url', models.URLField(blank=True, default='')),
                ('description', models.TextField(blank=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_resource_slug_per_tenant')],
            },
        ),
    ]
