# Generated by Django 6.1.1 on 2026-09-14 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_bookorder_classroutine_clubpost_clubcomment_feedpost_and_more'),
        ('tenants', '0007_tenant_footer_style_tenant_header_style'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='পরীক্ষার শিরোনাম (যেমন: ভেক্টর সাপ্তাহিক মডেল টেস্ট)', max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='পরীক্ষার সিলেবাস ও নির্দেশিকা')),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='পরীক্ষার সময়কাল (মিনিটে)')),
                ('pass_mark', models.DecimalField(decimal_places=2, default=40.0, help_text='পাস মার্ক বা পার্সেন্টেজ', max_digits=5)),
                ('negative_mark_per_question', models.DecimalField(decimal_places=2, default=0.25, help_text='প্রতি ভুল উত্তরের জন্য কাটা নম্বর (যেমন: 0.25)', max_digits=4)),
                ('total_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text='ঐচ্ছিক: কোনো নির্দিষ্ট কোর্সের সাথে যুক্ত করতে পারেন', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='courses.course')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('is_passed', models.BooleanField(default=False)),
                ('answers_json', models.JSONField(default=dict, help_text='Keyed by question_id: selected_option')),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='প্রশ্নটি লিখুন (ম্যাথ ফর্মুলা বা টেক্সট)')),
                ('image_url', models.URLField(blank=True, default='', help_text='ঐচ্ছিক: কোনো চিত্র বা ডায়াগ্রামের লিংক')),
                ('option_a', models.CharField(help_text='অপশন ক', max_length=500)),
                ('option_b', models.CharField(help_text='অপশন খ', max_length=500)),
                ('option_c', models.CharField(help_text='অপশন গ', max_length=500)),
                ('option_d', models.CharField(help_text='অপশন ঘ', max_length=500)),
                ('correct_option', models.CharField(choices=[('A', 'অপশন ক (A)'), ('B', 'অপশন খ (B)'), ('C', 'অপশন গ (C)'), ('D', 'অপশন ঘ (D)')], default='A', max_length=2)),
                ('explanation', models.TextField(blank=True, help_text='সঠিক উত্তরের ব্যাখ্যা ও সমাধান কৌশল')),
                ('marks', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.exam')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_exam_slug_per_tenant'),
        ),
    ]
