# Generated by Django 6.1.1 on 2026-09-13 09:12

import apps.tenants.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_courses', models.PositiveIntegerField(default=5, help_text='Maximum published courses permitted.')),
                ('max_students', models.PositiveIntegerField(default=250, help_text='Maximum enrolled students permitted.')),
                ('custom_domain_allowed', models.BooleanField(default=False, help_text='Allows white-label custom CNAME domain.')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of feature bullet points for pricing cards.')),
                ('is_popular', models.BooleanField(default=False, help_text='Highlight as Recommended/Most Popular tier.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price_monthly'],
            },
        ),
        migrations.AlterField(
            model_name='tenant',
            name='branding',
            field=models.JSONField(blank=True, default=apps.tenants.models.default_branding, help_text='JSON payload containing colors, logos, and custom landing page copy.'),
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TRIALING', '14-Day Free Trial'), ('ACTIVE', 'Active Subscription'), ('PAST_DUE', 'Past Due'), ('CANCELED', 'Canceled')], db_index=True, default='TRIALING', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='tenants.subscriptionplan')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant')),
            ],
        ),
    ]
