# Generated by Django 6.1.1 on 2026-09-14 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_banner_tenant_favicon_tenant_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='landing_template',
            field=models.CharField(choices=[('edtech_bangla', 'এডমিশন ও একাডেমি EdTech (ডিজাইন ১)'), ('modern_saas', 'মডার্ন টেক ও প্রো একাডেমি (ডিজাইন ২)'), ('classic_coaching', 'ক্লাসিক কোচিং সেন্টার ও লাইভ নোটিশ (ডিজাইন ৩)')], default='edtech_bangla', help_text='Selected landing page layout design for this academy storefront.', max_length=30),
        ),
        migrations.CreateModel(
            name='TenantMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Label displayed in navigation (e.g., 'কোর্সসমূহ')", max_length=100)),
                ('url', models.CharField(help_text="Path or external URL (e.g., '/courses/', '/books/', 'https://youtube.com')", max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in the navigation bar')),
                ('is_active', models.BooleanField(default=True, help_text='Visible in the public storefront header')),
                ('open_in_new_tab', models.BooleanField(default=False, help_text='Open link in a new browser tab')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='tenants.tenant')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
