# Generated by Django 6.1.1 on 2026-09-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_landing_template_tenantmenuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='footer_style',
            field=models.CharField(choices=[('footer_1', 'এডটেক পেমেন্ট ও অ্যাপ সমৃদ্ধ ফুটার (স্টাইল ১)'), ('footer_2', 'মডার্ন মাল্টি-কলাম ও নিউজলেটার ফুটার (স্টাইল ২)'), ('footer_3', 'ক্লাসিক ক্যাম্পাস ব্রাঞ্চ ও হেল্পলাইন ফুটার (স্টাইল ৩)')], default='footer_1', help_text='Selected footer layout style for this academy storefront.', max_length=30),
        ),
        migrations.AddField(
            model_name='tenant',
            name='header_style',
            field=models.CharField(choices=[('header_1', 'এডটেক নোটিশ ও হটলাইন টপবার (স্টাইল ১)'), ('header_2', 'মডার্ন ফ্ল্যাটিং গ্লাস হেডার (স্টাইল ২)'), ('header_3', 'ক্লাসিক একাডেমি ডুয়াল-টিয়ার হেডার (স্টাইল ৩)')], default='header_1', help_text='Selected header navigation style for this academy storefront.', max_length=30),
        ),
    ]
