# Generated by Django 6.1.1 on 2026-09-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_tenant_footer_style_tenant_header_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='android_apk',
            field=models.FileField(blank=True, help_text='Android App APK package uploaded for direct download by academy students.', null=True, upload_to='tenants/apks/'),
        ),
    ]
