# Generated by Django 6.1.1 on 2026-09-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_tenant_android_apk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['order', 'price_monthly']},
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='badge_text',
            field=models.CharField(blank=True, default='', help_text='Custom badge label e.g. ⭐ সর্বাধিক জনপ্রিয় or 🔥 সেরা অফার', max_length=50),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='billing_period',
            field=models.CharField(default='প্রতি মাস', help_text="Billing cycle label, e.g. 'প্রতি মাস' or '/month'", max_length=30),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='cta_text',
            field=models.CharField(default='১৪ দিনের ফ্রি ট্রায়াল শুরু করুন', help_text='Call to action button text', max_length=50),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Short description or target audience (e.g. ছোট একাডেমি ও শিক্ষকদের জন্য)', max_length=255),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Controls if this plan is visible in public pricing and registration.'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order in pricing tables.'),
        ),
    ]
