# Generated by Django 6.1.1 on 2026-09-13 08:25

import apps.tenants.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Public brand name of the academy.', max_length=150)),
                ('slug', models.SlugField(help_text='Used for the subdomain: [slug].platform.com or [slug].localhost', max_length=63, unique=True, validators=[django.core.validators.RegexValidator(message='Subdomain must be lowercase alphanumeric and may contain hyphens.', regex='^[a-z0-9](?:[a-z0-9\\-]{0,61}[a-z0-9])?$')])),
                ('custom_domain', models.CharField(blank=True, db_index=True, help_text='Custom CNAME domain (e.g., learn.mybrand.com). Normalized to lowercase.', max_length=255, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Controls if the academy is reachable and active.')),
                ('branding', models.JSONField(blank=True, default=apps.tenants.models.default_branding, help_text='JSON payload containing colors, logos, and UI tokens.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
