# Generated by Django 6.1.1 on 2026-09-13 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='owner',
            field=models.ForeignKey(help_text='Primary platform user who owns this academy.', on_delete=django.db.models.deletion.PROTECT, related_name='owned_tenants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['slug', 'is_active'], name='tenants_ten_slug_7c647c_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['custom_domain', 'is_active'], name='tenants_ten_custom__a56139_idx'),
        ),
    ]
