# Generated by Django 6.1.1 on 2026-09-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_subscriptionplan_alter_tenant_branding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='custom_domain_token',
            field=models.CharField(blank=True, default='', help_text='Random challenge token expected in _saascourse-challenge TXT record.', max_length=64),
        ),
        migrations.AddField(
            model_name='tenant',
            name='custom_domain_verified',
            field=models.BooleanField(default=False, help_text='True when DNS TXT / CNAME ownership verification has succeeded.'),
        ),
    ]
