# Generated by Django 6.1.1 on 2026-09-14 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_custom_domain_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='banner',
            field=models.ImageField(blank=True, help_text='Hero cover banner image displayed across the storefront landing.', null=True, upload_to='tenants/banners/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Browser favicon icon (32x32 or 64x64 .png / .ico).', null=True, upload_to='tenants/favicons/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, help_text='Square or horizontal academy brand logo.', null=True, upload_to='tenants/logos/'),
        ),
        migrations.CreateModel(
            name='TenantSMSSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('SSL_WIRELESS', 'SSL Wireless (Bangladesh)'), ('GREENWEB', 'Greenweb SMS (Bangladesh)'), ('MIM_SMS', 'MimSMS (Bangladesh)'), ('TWILIO', 'Twilio Global'), ('GENERIC', 'Generic HTTP GET/POST API')], default='SSL_WIRELESS', help_text='Selected SMS Gateway Service Provider', max_length=30)),
                ('is_enabled', models.BooleanField(default=False, help_text='Enable live SMS sending for this coaching center.')),
                ('sender_id', models.CharField(blank=True, default='', help_text='Approved Sender ID, Masking name, or Twilio Phone Number.', max_length=60)),
                ('api_key', models.CharField(blank=True, default='', help_text='API Token, User Token, or Twilio Account SID.', max_length=255)),
                ('api_secret', models.CharField(blank=True, default='', help_text='API Secret Password, Twilio Auth Token, or Client Secret.', max_length=255)),
                ('api_url', models.URLField(blank=True, default='', help_text='Custom gateway HTTP endpoint (required for Generic HTTP API).', max_length=500)),
                ('template_enrollment', models.TextField(blank=True, default="Dear {student_name}, congratulations on enrolling in '{course_title}' at {academy_name}! Start learning now.", help_text='Template for course enrollment confirmation SMS.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_setting', to='tenants.tenant')),
            ],
        ),
    ]
